# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bib', '0001_initial'),
        ('places', '0001_initial'),
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=300)),
                ('filename', models.CharField(blank=True, max_length=300)),
                ('date_analogue', models.CharField(blank=True, max_length=300)),
                ('date_digitization', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('location_analogue', models.CharField(blank=True, max_length=300)),
                ('place_digizization', models.CharField(blank=True, max_length=300)),
                ('filesize', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('abbreviation', models.CharField(blank=True, max_length=300)),
                ('identifier', models.CharField(blank=True, max_length=300)),
                ('parent_institution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('identifier', models.CharField(blank=True, max_length=300)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='digital_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_format', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='document',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='document',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='document',
            name='reference',
            field=models.ManyToManyField(blank=True, to='bib.Book'),
        ),
        migrations.AddField(
            model_name='document',
            name='topic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_group', to='vocabs.SkosConcept'),
        ),
    ]
